#!/command/with-contenv bash

source /assets/functions/00-container
# shellcheck disable=SC2034
PROCESS_NAME="incron"

print_notice "Enabling incron (sysadmin hooks)"
mkdir -p /var/spool/asterisk/incron
chown -R asterisk: /var/spool/asterisk/incron
service_start 09-incron

liftoff
